# Generated by Django 4.0.3 on 2022-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('registration_no', models.IntegerField(unique=True)),
                ('passing_year', models.IntegerField()),
                ('branch', models.CharField(choices=[('COMPS', 'Computer ENGINEERING'), ('IT', 'INFORMATION TECHNOLOGY ENGINEERING'), ('EXTC', 'ELECTRONICS AND TELECOMMUNICATION ENGINEERING'), ('ETRX', 'ELECTRONICS ENGINEERING'), ('AIDS', 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE ENGINEERING')], max_length=5)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
