# Generated by Django 4.0.3 on 2022-03-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alumni_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='branch',
            field=models.CharField(choices=[('COMPS', 'COMPUTER ENGINEERING'), ('IT', 'INFORMATION TECHNOLOGY ENGINEERING'), ('EXTC', 'ELECTRONICS AND TELECOMMUNICATION ENGINEERING'), ('ETRX', 'ELECTRONICS ENGINEERING'), ('AIDS', 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE ENGINEERING')], max_length=5),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='image',
            field=models.ImageField(null=True, upload_to='alumnis_photos/'),
        ),
    ]
