# Generated by Django 4.0.3 on 2022-03-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_alumni_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
