# Generated by Django 4.0.3 on 2022-03-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_alumni_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='image',
        ),
        migrations.AddField(
            model_name='alumni',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
