# Generated by Django 4.0.3 on 2022-03-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_remove_alumni_image_alumni_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('schedule', models.DateTimeField()),
                ('description', models.TextField()),
                ('event_image', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('decription', models.TextField()),
            ],
        ),
    ]
